### ISSUE TITLE
postgres -> source-postgres

### ISSUE THREAD

**Issue by tejasmanohar** [segment-sources/postgres#3]
For consistency w/ https://github.com/segment-sources/mysql/issues/4

**Comment by zachlatta** [comment]
:+1: 

Support this as well.

**Comment by llexical** [comment]
Could we please do this, if I have postgres installed (not the segment postgres pkg) even if I have my Go bin folder added to my PATH I need to run `$GOPATH/bin/postgres` to run the correct file.

**Comment by sperand-io** [comment]
:)
